
# 发送统计数据到 influxdb的地址
stats-enabled: true
stats-ip: 127.0.0.1 
stats-port: 20044
stats-interval: 10

# 写入数据的时间跨度, 秒
time-interval: 60
# 写入多少条，时间增加time-interval
time-interval-write: 1000000
# 开始写入的数据的时间戳和当前时间的偏差
time-offset: 0

# 共写入多少行后结束
write-total-count: 1000000
# 循环写入次数, 默认1，每次写write-total-count条
writer-loop-count: 1
# 几个线程同时写
write-thread-count: 10

# 发送数据到写队列的速度 条/s，多线程之和, 防止发送过快后，导致写入队列满，就会丢失
send-rate: 100000

# 每多大数据 批量发送一次ck写操作
batch-size: 100000
# 写入队列的长度
queue-size: 10000000

engine: MergeTree()
storage: default
ttl: 7

# 写入的数据库名称, 若不存在自动创建
db-name: test
# 写入的table名称, 若不存在自动创建
table-name: test_array_1

# 写入的column信息, 默认写入time列，作为partition, 默认1天为一个partition
columns:
- name: string_table_8_32
  type: String
  value-range: [8, 32, 100]
- name: array_names_8
  type: Array(String)
  value-range: [8, 8, 2,8,8]
- name: array_names_8
  type: Array(LowCardinality(String))
  value-range: [8, 8, 2,8,8]
#- name: array_values_bloom_8
#  type: String
#  index: bloom_filter
#  value-range: [8, 32, 1000,8,8]
#- name: array_values_set_8
#  type: String
#  index: set(300)
#  value-range: [8, 32, 1000,8,8]
